version: '1.0'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: consortium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: